#!/usr/bin/env python

import sys
import re

def sortby(x):
   return int(x.split()[0])

def main():

   if len(sys.argv) == 3:

      matches = []
      iterations = []
      totals = []

      f = open(sys.argv[1])

      for line in f:

         if line.startswith('DSC'):
            m = re.search(sys.argv[2], line)
            if m:
               s = line.split(sys.argv[2])[1].split(',')[0];
               l = re.split(r'<\d+>', line.split(sys.argv[2])[0])[1];

               #print s;
               if l not in matches:
                  matches.append(l);
                  iterations.append(1);
                  totals.append(int(s));
               else:
                  iterations[matches.index(l)] += 1;
                  totals[matches.index(l)] += int(s);

      f.close()

      results = []

      i = 0;
      for m in matches:
         results.append  ( str(totals[i]) + ' ' + str(iterations[i]) + 'x ' + m );
         i = i + 1;

      results.sort(key = sortby, reverse=True);

      for r in results:
         print r;

   else:
      print("Usage: %s tdifile pattern" % sys.argv[0])

if __name__ == "__main__":
   main()