#!/usr/bin/env python

import sys
import re

NOTE = 7

def main():

   if len(sys.argv) >= 3:

      matches = []
      for match in sys.argv[2:]:
         matches.append(match)

      f = open(sys.argv[1])

      # find highest note id
      highestnoteid = 0
      for line in f:
         if line.startswith('NAM') and int(line.split(' ')[1]) == NOTE:
            if int(line.split(' ')[2]) > highestnoteid:
               highestnoteid = int(line.split(' ')[2])
      if highestnoteid == 0:
         highestnoteid = NOTE * 1000

      sys.stderr.write('highest note id is:%d\n' % highestnoteid)
      nextnoteid = highestnoteid + 1


      f.seek(0)

      notenams = []
      nams = []


      for line in f:

         if line.startswith('OCC') or line.startswith('STA'):

            line = f.next()
            dscwords = line.split()

            for match in matches:

               if re.compile(match).findall(dscwords[3]):

                  #sys.stderr.write('match:%s\n' % match)
                  #sys.stderr.write('in:%s\n' % dscwords[3])

                  if not match in notenams:
                     notenams.append(match)
                     nams.append("NAM 7 %d %s" % ( (nextnoteid + matches.index(match)), match))

      f.seek(0)


      # pass 2
      first = True;
      printnotenams = True

      for line in f:

         if printnotenams:
            if line.startswith('NAM'):
               for nam in nams:
                     print nam
               printnotenams = False

         print line,

         if line.startswith('OCC') or line.startswith('STA'):
            tstamp = line.split()[3]

            line = f.next()
            print line,
            dscwords = line.split()

            for match in matches:

               result = re.compile(match).findall(dscwords[3])
               if result:

                  #sys.stderr.write('\n\nmatch:%s\n' % match)
                  #sys.stderr.write('in:%s\n' % dscwords[3])

                  #sys.stderr.write('result:%s\n' % result)
                  #sys.stderr.write('OCC 7 %d %d\n' % (nextnoteid + matches.index(match), int(tstamp)))

                  print 'OCC 7 %d' % (nextnoteid + matches.index(match)), tstamp
                  print 'DSC 0 0', dscwords[3]

      f.close()

   else:
      print("Usage: %s tdifile pattern1 pattern2..." % sys.argv[0])

if __name__ == "__main__":
   main()