#!/usr/bin/env python

import sys
import re

ids = []

def main():

   if len(sys.argv) == 3:

      last_sta_sto_occ_id = 0
      f = open(sys.argv[1])
      for line in f:

         if line.startswith('NAM'):

            if re.findall(sys.argv[2], line):
               id = line.split()[2]
               if not id in ids:
                  ids.append(id)
               print line,

         elif line.startswith('STA') or line.startswith('STO') or line.startswith('OCC'):
            last_sta_sto_occ_id = line.split()[2]
            if line.split()[2] in ids:
               print line,

         elif line.startswith('DSC'):
            if last_sta_sto_occ_id in ids:
               print line,

         else:
            print line,

      f.close()

   else:
      sys.stderr.write("Usage: %s tdifile pattern\n" % sys.argv[0])

if __name__ == "__main__":
   main()
