#!/usr/bin/env python

import sys
import re


idstorm = []

def main():

   if len(sys.argv) == 3:

      f = open(sys.argv[1])

         if line.startswith('NAM'):
            if re.search(sys.argv[2], line):
               id = (int)line.split()[2]
               if not id in ids
                  ids.append(id)

      for line in f:

         if line.startswith('NAM'):
            if re.search(sys.argv[2], line):
               id = (int)line.split()[2]
               if not id in ids
                  ids.append(id)
            else:
               print line,

         elif line.startswith('STA') or line.startswith('STO') or line.startswith('OCC'):
            if not line.split()[2] in ids:
            print line,

         elif line.startswith('DSC'):
            if re.search(sys.argv[2], line):
            else:
               print line,

         else:
            print line,

      f.close()

   else:
      print("Usage: %s tdifile pattern" % sys.argv[0])

if __name__ == "__main__":
   main()
